# Generated by Django 4.1.4 on 2022-12-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='anonymous_only',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='login_required',
        ),
    ]
