# Generated by Django 4.1.4 on 2022-12-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menu_base_url_remove_menuitem_anonymous_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='base_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base URL'),
        ),
    ]
